apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-iqss-data
  namespace: uat
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi
