apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-iqss          # nom du déploiement
  namespace: default
spec:
  replicas: 1             # nombre de pods à lancer
  selector:
    matchLabels:
      app: api-iqss
  template:
    metadata:
      labels:
        app: api-iqss
    spec:
      initContainers:  # ✅ Exécuté AVANT le container principal
      - name: clean-docs
        image: busybox:1.35
        command: ["/bin/sh"]
        args:
        - -c
        - |
          echo "🧹 Vidage docs existants..."
          rm -rf /data/* /data/.[!.]* /data/..?*
          echo "✅ Docs vidés, prêt pour déploiement"
        volumeMounts:
        - name: data-volume
          mountPath: /data  # Même volume
      containers:
      - name: api-iqss
        image: 10.2.240.5:8080/production/api-iqss:prod-768102b0d7030f1b38c3ae09cc1c221b86cf5d95
        ports:
        - containerPort: 8080   # port sur lequel FastAPI écoute
        env:
        - name: APP_ENV
          value: "production"
        envFrom:
        - secretRef:
            name: api-iqss-secret
        volumeMounts:
        - name: data-volume
          mountPath: /api-iqss/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: api-iqss-data
      imagePullSecrets:
      - name: harbor-secret     # secret pour s'authentifier à Harbor
